export const HybeFlexAppMode = {
  HYBEFLEX_APP_MODE_DEBUG: -1,
  HYBEFLEX_APP_MODE_LOADING: 0, // Always needs to be 0
  HYBEFLEX_APP_MODE_VIDEOSCREEN: 1,
  HYBEFLEX_APP_MODE_STUDENT: 2,
  HYBEFLEX_APP_MODE_LECTURER: 3,
  HYBEFLEX_APP_MODE_INTERPRETER: 4,
  HYBEFLEX_APP_MODE_AUTOVIDEO: 5,
  HYBEFLEX_APP_MODE_NORMAL: 99,
}
